[pi0disp]
name = "2.4 inch IPS LCD 240x320 SPI ST7789 full-color"
width = 240
height = 320
rotation = 270
x_offset = 0
y_offset = 0
# y_offset = 20 # 画面下部が更新されない場合に試してください
# y_offset = 34 # モジュールによって異なる場合があります

# 色設定 (色が正しくない場合に調整してください)
#invert = true   # 背景を黒にする場合は true
#bgr = false     # 赤と青が逆の場合は false (bgr=true) に設定
bgr = false
invert = true

[pi0disp.spi]
cs = 8
rst = 25
dc = 24
bl = 23
#bl = 0
channel = 0
speed_hz = 4_000_000
